config/routes.rb
Rails.application.routes.draw do

  get 'admin/index'


  get 'contact', to:'contact#index'

  post 'contact', to:'contact#mail'

  resources :posts do
    resources :comments
  end


  devise_for :users
  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments

  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged

  def slug_candidates
    [
      :title,
      [:title, :content],
    ]
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :posts
   has_many :comments

   def admin?
    has_role?(:admin)
   end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
before_action :checkIsAdmin, only: :index

  def index
    @posts = Post.all
    @users = User.all
  end

  private
  def checkIsAdmin
    if current_user.user_type != 'admin'
     flash[:warning] = "You Cannot Access This Page"
     redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @post = Post.friendly.find(params[:post_id])
    @comment.post_id = @post.id

    respond_to do |format|
      if @comment.save
        # redirect to post relating to this controller
        format.html { redirect_to post_path(@comment.post.id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end

  def mail

    if params[:contact]
      email =  params[:contact][:email]
      message = params[:contact][:message]

      if email.present? || message.present?
        # Tell the UserMailer to send a welcome email after save
        ContactMailer.send_contact_email(email, message).deliver_now
        redirect_to '/contact', notice: "Email sent!"
      else
        flash[:warning] = "Please fill out the form"
        redirect_to '/contact'
      end

    end

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :own_post, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    # To setup the variable for our comment form
    @post = Post.friendly.find(params[:id])
    @comment = Comment.new

    @comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize @post
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :user_id)
    end

    def own_post
     unless current_user == @post.user
    #  flash[:alert] = "You cannot edit this item."
    #  format.html { redirect_to root_path, notice: 'You Cannot Edit This Item' }
    flash[:warning] = "You Cannot Edit This Item"
    redirect_to root_path
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    end
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/index.html.erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>


<h1>Posts</h1>
<div class="panel panel-default">
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>

        <td><%= link_to 'Show', post, class: "btn btn-default" %></td>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>


      </tr>
    <% end %>
  </tbody>
</table>
</div>

<h1>Users</h1>
<div class="panel panel-default">
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Email</th>
      <th>User Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.user_type %></td>

        <td><%#= link_to 'Show', post, class: "btn btn-default" %></td>
        <td><%#= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %></td>
        <%#= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        <td><%= link_to 'Delete', user_registration_path, :confirm => 'Are you sure you want to destroy your account?', :method => :delete, class: "btn btn-danger" %></td>


      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, comment]) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :post_id %>
    <%#= f.hidden_field :post_id, value: @post.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.post %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/contact/index.html.erb
<div class="col-md-6">

  <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% elsif flash[:warning] %>
      <div class="alert alert-danger"><%= flash[:warning] %></div>
    <% else %>
  <% end %>

<h1>Contact Us</h1>

<%= simple_form_for :contact do |f| %>
    <%= f.input :email, placeholder: 'type email here' %>
    <%= f.input :message, placeholder: 'type message here', :as => :text %>
    <%= f.button :submit, "Send" %>
<% end %>

</div>

app/views/contact/mail.html.erb
<h1>Contact#mail</h1>
<p>Find me in app/views/contact/mail.html.erb</p>

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <%= link_to("Logout #{current_user.email}", destroy_user_session_path, :method => :delete) %>
<% else %>
  <%= link_to('Login', new_user_session_path)  %>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <!-- <a class="navbar-brand">LambTown</a> -->
      <!-- <img class="navbar-left" alt="Logo" src="/assets/LambLogoTextHorz.png" style="height: 50px" /> -->
      <%=link_to cl_image_tag("LambLogoTextHorz_jro4vz.png"), root_path, class: "navbar-left logo-img"%>

    </div>
    <ul class="nav navbar-nav">
      <li class="<%= 'active' if params[:controller] == 'pages' %>"><%= link_to "Home", root_path %></li>
      <li class="<%= 'active' if params[:controller] == 'posts' %>"><%= link_to 'Posts', posts_path %></li>
      <li class="<%= 'active' if params[:controller] == 'contact' %>"><%= link_to 'Contact', contact_path %></li>
      <li class="<%= 'active' if params[:controller] == 'admin' %>"><%= link_to 'Admin', admin_index_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= render 'layouts/login_items' %></li>
      <li><%= render 'layouts/registration_items' %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
      <div class="alert alert-<%=key%>">
            <%= value %>
      </div>
<% end %>

app/views/layouts/_registration_items.html.erb
<% if user_signed_in? %>
  <%= link_to('Edit registration', edit_user_registration_path) %>
<% else %>
  <%= link_to('Register', new_user_registration_path)  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>Lambtown</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
    <%= render partial: 'layouts/notice', flash: flash %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Lamb Town</h1>
<p>We are proud young lambs</p>

<p><%= link_to 'View Posts', posts_path %></p>

<% if user_signed_in? %>
  <p><%= link_to("Logout", destroy_user_session_path, :method => :delete) %></p>
<% else %>
  <p><%= link_to('Login', new_user_session_path)  %></p>
<% end %>
<% if user_signed_in? %>
  <p><%= link_to('Edit registration', edit_user_registration_path) %></p>
<% else %>
  <p><%= link_to('Register', new_user_registration_path)  %></p>
<% end %>


<%= cl_image_tag("LambTownLogo_cvjjyt.png")%>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<div class="panel panel-default">
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user.email %></td>

        <td><%= link_to 'Show', post, class: "btn btn-default" %></td>
        <%if post.user == current_user%>
        <td><%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %></td>
        <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
        <%else%>
        <td></td>
        <td></td>
        <%end%>

      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Post', new_post_path, class: "btn btn-default" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user.email %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<%= render 'comments/form', comment: @comment, post: @post %>

<% @comments.each do |comment| %>
<p><%= comment.user.email %></p> - <p><%= comment.created_at %></p>
<p><%= comment.content %></p>
<% end %>